packages:
  - apps/*
  - packages/*

catalog:
  dotenv: 16.3.1
  zod: 3.25.67
  tsx: 4.19.2
  axios: 1.12.1
  dayjs: 1.11.10
  lodash-es: 4.17.21
  "@types/lodash-es": 4.17.12
  tsdown: 0.15.6
  "@prisma/client": 7.1.0
  "prisma": 7.1.0
  "@prisma/adapter-pg": 7.1.0
  "decimal.js": 10.4.3